sudo: required

services:
- docker

env:
  global:
    - CURRENT_GIT_BRANCH=$TRAVIS_BRANCH

script:
- make build
- make test

deploy:
- provider: script
  script: make deploy
  on:
    condition: $TRAVIS_PULL_REQUEST = false
